### ISSUE TITLE
Unable to run on C.H.I.P.

### ISSUE THREAD

**Issue by jadolg** [xwiki-labs/cryptpad#217]
I installed everything in [C.H.I.P.](https://docs.getchip.com/chip_pro.html) and I'm still getting this error when trying to run:
```
chip@localhost:~/cryptpad$ node server

/home/chip/cryptpad/server.js:42
const clone = (x) => (JSON.parse(JSON.stringify(x)));
                   ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
chip@localhost:~/cryptpad$ 
```

**Comment by kpcyrd** [comment]
It seems you're using a very old nodejs version that doesn't have support for arrow functions. You could try transpiling the project to ES5 with babel or upgrade your nodejs.

**Comment by ansuz** [comment]
@kpcyrd, thanks for your help!

We don't test CryptPad on anything older than node 6.6.0 (as per [the installation docs](https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide)), and we're considering switching to a newer version of node for improved performance.
