### ISSUE TITLE
const Crypto = require('crypto'); = SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by sammcj** [xwiki-labs/cryptpad#31]
Howdy,

I generally try to avoid running nodejs apps whenever possible but wanted to give this one a shot, however this error message is not overly helpful.

Is anyone ale to shed some light on this for me?

* CentOS 7
* Followed 'To install:...'
* npm: 2.15.1
* node: nodejs-0.10.46-1nodesource.el7.centos.x86_64

```
[nginx@nas]/usr/share/nginx/html/cryptpad% node ./server.js

/usr/share/nginx/html/cryptpad/NetfluxWebsocketSrv.js:2
const Crypto = require('crypto');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/share/nginx/html/cryptpad/server.js:9:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by cjdelisle** [comment]
It looks like your version of node is the issue. The latest version is 6.5.0 and the current LTS version is 4.5.0.  0.10.46 is really a security patch release of a version from 2013 which is over 1/3 the age of node.

I would recommend using nvm to install node. You can install it using the instructions here: https://github.com/creationix/nvm#install-script  once nvm is installed use `nvm install 6.5.0` to install node.

**Comment by ansuz** [comment]
Instructions have been added to the readme for installing node via nvm.
