### ISSUE TITLE
Docker  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by gerroon** [xwiki-labs/cryptpad#377]
Hi I followed https://github.com/xwiki-labs/cryptpad/wiki/Docker to build and run docker

I am running it with `docker run -p 5080:3000 --name cryptpad xwiki/cryptpad`

```

Creating config.js
Linking config.js
Using secure websockets: false
Using storage adapter: './storage/file'
Logging to stdout: true
You can configure the administrator email (adminEmail) in your config/config.js file
FRESH MODE ENABLED
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EAFNOSUPPORT :::3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:19)
    at listen (net.js:1307:10)
    at net.js:1417:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:613:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```

**Comment by ansuz** [comment]
Does it help if you change `httpAddress` in your config from `'::'` to `'0.0.0.0'` ?

**Comment by gerroon** [comment]
Hi

thanks for the reply. Where is the address setting?

**Comment by ansuz** [comment]
In your configuration file: https://github.com/xwiki-labs/cryptpad/blob/master/config/config.example.js#L73
