### ISSUE TITLE
Setup failing at `npm install`

### ISSUE THREAD

**Issue by doodlebug70** [xwiki-labs/cryptpad#472]
I am trying to install Cryptpad on Debian 9  with the following software

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch
```

```
$ dpkg -l | grep nodejs  
ii  nodejs   11.15.0-1nodesource1   amd64  Node.js event-based server-side javascript engine
```

```
$ npm --version
6.7.0
```

```
$ bower --version
1.8.8
```

I am following the install instructions from this github.  The cloning and `cd`'ing work fine (woo :-) ) but I am getting stuck on `npm install`  which throws the following error

```
$ npm install
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cryptpad/.npm/_logs/2019-12-02T09_12_58_773Z-debug.log
```

Looking in this log file gives details of installing and then ends with the following error

```
2077 verbose stack Error: premature close
2077 verbose stack     at PassThrough.onclose (/usr/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
2077 verbose stack     at PassThrough.emit (events.js:198:15)
2077 verbose stack     at emitCloseNT (internal/streams/destroy.js:68:8)
2077 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:81:17)
2078 verbose cwd /srv/cryptpad
2079 verbose Linux 4.9.0-11-amd64
2080 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
2081 verbose node v11.15.0
2082 verbose npm  v6.7.0
2083 error premature close
2084 verbose exit [ 1, true ]
```

Would anyone have any suggestions for what direction to look in to further troubleshoot?

**Comment by ansuz** [comment]
Are you still experiencing this issue?
