### ISSUE TITLE
Getting this error while trying to start CryptPad locally

### ISSUE THREAD

**Issue by rOmAn2193** [xwiki-labs/cryptpad#616]
Getting this error when trying to run node server to start CryptPad locally

```
node server
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/Users/roman-puzey/Documents/CryptPad/cryptpad/config/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by ansuz** [comment]
It looks like you're trying to run `node server` from within your `cryptpad/config/` directory. The `server.js` script is located in the parent directory.

Alternatively, you can run `npm start` from anywhere in the CryptPad repo to launch the server.
