### ISSUE TITLE
error causes server to die

### ISSUE THREAD

**Issue by cjdelisle** [xwiki-labs/cryptpad#7]
istening on port 3000
DB connected
[VDThbt+cgFs=:y] registered
[8QxSQ/FfUH8=:y] registered
Removing [8QxSQ/FfUH8=] from channel [u73giBH2D2]
Removing [VDThbt+cgFs=] from channel [u73giBH2D2]
Removing empty channel [u73giBH2D2]
[7T1mGr/H3H4=:y] registered
[7T1mGr/H3H4=:y] registered
[7T1mGr/H3H4=:y] registered
[7T1mGr/H3H4=:y] registered
[7T1mGr/H3H4=:y] registered
[7T1mGr/H3H4=:y] registered
[7T1mGr/H3H4=:y] registered
[xBcR2xfzpLw=:y] registered
Removing [xBcR2xfzpLw=] from channel [u73giBH2D2]
Removing [7T1mGr/H3H4=] from channel [u73giBH2D2]
Error: not opened
    at WebSocket.send (/home/luser/cryptpad/node_modules/ws/lib/WebSocket.js:181:16)
    at sendMsg (/home/luser/cryptpad/ChainPadSrv.js:61:12)
    at /home/luser/cryptpad/ChainPadSrv.js:68:17
    at Array.forEach (native)
    at /home/luser/cryptpad/ChainPadSrv.js:66:17
    at /home/luser/cryptpad/Storage.js:29:9
    at /home/luser/cryptpad/node_modules/mongodb/lib/collection.js:345:5
    at handleCallback (/home/luser/cryptpad/node_modules/mongodb/lib/utils.js:93:12)
    at /home/luser/cryptpad/node_modules/mongodb/lib/collection.js:492:5
    at /home/luser/cryptpad/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:754:13

/home/luser/cryptpad/node_modules/mongodb/lib/utils.js:95
    process.nextTick(function() { throw err; });
                                        ^
ReferenceError: userPass is not defined
    at /home/luser/cryptpad/ChainPadSrv.js:71:33
    at Array.forEach (native)
    at /home/luser/cryptpad/ChainPadSrv.js:66:17
    at /home/luser/cryptpad/Storage.js:29:9
    at /home/luser/cryptpad/node_modules/mongodb/lib/collection.js:345:5
    at handleCallback (/home/luser/cryptpad/node_modules/mongodb/lib/utils.js:93:12)
    at /home/luser/cryptpad/node_modules/mongodb/lib/collection.js:492:5
    at /home/luser/cryptpad/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:754:13
    at Callbacks.emit (/home/luser/cryptpad/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:90:3)
    at null.messageHandler (/home/luser/cryptpad/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:219:23)

**Comment by ansuz** [comment]
Closing as I have never seen this error.

**Comment by kpcyrd** [comment]
This is probably #6, which has been fixed.
